unit CustomerActiveRecord;

interface

uses
  MVCFramework.ActiveRecord,
  MVCFramework.Serializer.Commons,
  MVCFramework.SQLGenerators.MySQL,
  Customer, CustomerContextIntf, EntityActiveRecord;

type

  [MVCNameCase(ncPascalCase)]
  [MVCTable('customer')]
  TCustomerActiveRecord = class(TEntityActiveRecord, ICustomerContext)
  private
    [MVCTableField('ID', [foPrimaryKey, foAutoGenerated])]
    FId: Integer;
    [MVCTableField('FIRST_NAME')]
    FFirstName: string;
    [MVCTableField('LAST_NAME')]
    FLastName: string;
    [MVCTableField('EMAIL')]
    FEmail: string;

    function GetId: Integer;
    procedure SetId(const AId: Integer);
    function GetFirstName: string;
    procedure SetFirstName(const AFirstName: string);
    function GetLastName: string;
    procedure SetLastName(const ALastName: string);
    function GetEmail: string;
    procedure SetEmail(const AEmail: string);
  public
    constructor Create; overload;
    constructor Create(const ACustomer: TCustomer); overload;
  
    property Id: Integer read GetId write SetId;
    property FirstName: string read GetFirstName write SetFirstName;
    property LastName: string read GetLastName write SetLastName;
    property Email: string read GetEmail write SetEmail;
  end;

implementation

{ TCustomerActiveRecord }

constructor TCustomerActiveRecord.Create(const ACustomer: TCustomer);
begin                    
  inherited Create(True);    

  Id := ACustomer.Id;
  FirstName := ACustomer.FirstName;
  LastName := ACustomer.LastName;
  Email := ACustomer.Email;  
end;

constructor TCustomerActiveRecord.Create;
begin
  inherited Create(True);
end;

function TCustomerActiveRecord.GetEmail: string;
begin
  Result := FEmail;
end;

function TCustomerActiveRecord.GetFirstName: string;
begin
  Result := FFirstName;
end;

function TCustomerActiveRecord.GetId: Integer;
begin
  Result := FId;
end;

function TCustomerActiveRecord.GetLastName: string;
begin


  Result := FLastName;
end;

procedure TCustomerActiveRecord.SetEmail(const AEmail: string);
begin
  FEmail := AEmail;
end;

procedure TCustomerActiveRecord.SetFirstName(const AFirstName: string);
begin
  FFirstName := AFirstName;
end;

procedure TCustomerActiveRecord.SetId(const AId: Integer);
begin
  FId := AId;
end;

procedure TCustomerActiveRecord.SetLastName(const ALastName: string);
begin
  FLastName := ALastName;
end;

end.
